//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var Errors_ttypes = require('./Errors_types');


var ttypes = require('./AdminAuth_types');
//HELPER FUNCTIONS AND STRUCTURES

var AdminAuthService_authorizeRequest_args = function(args) {
  this.userId = null;
  this.requestUrl = null;
  if (args) {
    if (args.userId !== undefined && args.userId !== null) {
      this.userId = args.userId;
    }
    if (args.requestUrl !== undefined && args.requestUrl !== null) {
      this.requestUrl = args.requestUrl;
    }
  }
};
AdminAuthService_authorizeRequest_args.prototype = {};
AdminAuthService_authorizeRequest_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.userId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.requestUrl = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AdminAuthService_authorizeRequest_args.prototype.write = function(output) {
  output.writeStructBegin('AdminAuthService_authorizeRequest_args');
  if (this.userId !== null && this.userId !== undefined) {
    output.writeFieldBegin('userId', Thrift.Type.STRING, 1);
    output.writeString(this.userId);
    output.writeFieldEnd();
  }
  if (this.requestUrl !== null && this.requestUrl !== undefined) {
    output.writeFieldBegin('requestUrl', Thrift.Type.STRING, 2);
    output.writeString(this.requestUrl);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AdminAuthService_authorizeRequest_result = function(args) {
  this.success = null;
  this.userException = null;
  this.systemException = null;
  if (args instanceof Errors_ttypes.UserException) {
    this.userException = args;
    return;
  }
  if (args instanceof Errors_ttypes.SystemException) {
    this.systemException = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.userException !== undefined && args.userException !== null) {
      this.userException = args.userException;
    }
    if (args.systemException !== undefined && args.systemException !== null) {
      this.systemException = args.systemException;
    }
  }
};
AdminAuthService_authorizeRequest_result.prototype = {};
AdminAuthService_authorizeRequest_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.userException = new Errors_ttypes.UserException();
        this.userException.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.systemException = new Errors_ttypes.SystemException();
        this.systemException.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AdminAuthService_authorizeRequest_result.prototype.write = function(output) {
  output.writeStructBegin('AdminAuthService_authorizeRequest_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  if (this.userException !== null && this.userException !== undefined) {
    output.writeFieldBegin('userException', Thrift.Type.STRUCT, 1);
    this.userException.write(output);
    output.writeFieldEnd();
  }
  if (this.systemException !== null && this.systemException !== undefined) {
    output.writeFieldBegin('systemException', Thrift.Type.STRUCT, 2);
    this.systemException.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AdminAuthServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
AdminAuthServiceClient.prototype = {};
AdminAuthServiceClient.prototype.seqid = function() { return this._seqid; };
AdminAuthServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
AdminAuthServiceClient.prototype.authorizeRequest = function(userId, requestUrl, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_authorizeRequest(userId, requestUrl);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_authorizeRequest(userId, requestUrl);
  }
};

AdminAuthServiceClient.prototype.send_authorizeRequest = function(userId, requestUrl) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('authorizeRequest', Thrift.MessageType.CALL, this.seqid());
  var args = new AdminAuthService_authorizeRequest_args();
  args.userId = userId;
  args.requestUrl = requestUrl;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AdminAuthServiceClient.prototype.recv_authorizeRequest = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AdminAuthService_authorizeRequest_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.userException) {
    return callback(result.userException);
  }
  if (null !== result.systemException) {
    return callback(result.systemException);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('authorizeRequest failed: unknown result');
};
var AdminAuthServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
AdminAuthServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
AdminAuthServiceProcessor.prototype.process_authorizeRequest = function(seqid, input, output) {
  var args = new AdminAuthService_authorizeRequest_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.authorizeRequest.length === 2) {
    Q.fcall(this._handler.authorizeRequest, args.userId, args.requestUrl)
      .then(function(result) {
        var result_obj = new AdminAuthService_authorizeRequest_result({success: result});
        output.writeMessageBegin("authorizeRequest", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof Errors_ttypes.UserException || err instanceof Errors_ttypes.SystemException) {
          result = new AdminAuthService_authorizeRequest_result(err);
          output.writeMessageBegin("authorizeRequest", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("authorizeRequest", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.authorizeRequest(args.userId, args.requestUrl, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof Errors_ttypes.UserException || err instanceof Errors_ttypes.SystemException) {
        result_obj = new AdminAuthService_authorizeRequest_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("authorizeRequest", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("authorizeRequest", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
