//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var Errors_ttypes = require('./Errors_types');
var AdminTag_ttypes = require('./AdminTag_types');
var AdminMenu_ttypes = require('./AdminMenu_types');


var ttypes = module.exports = {};
var AdminUser = module.exports.AdminUser = function(args) {
  this.id = null;
  this.name = null;
  this.passwd = null;
  this.team = null;
  this.is_use = null;
  this.reg_date = null;
  this.email = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.name !== undefined && args.name !== null) {
      this.name = args.name;
    }
    if (args.passwd !== undefined && args.passwd !== null) {
      this.passwd = args.passwd;
    }
    if (args.team !== undefined && args.team !== null) {
      this.team = args.team;
    }
    if (args.is_use !== undefined && args.is_use !== null) {
      this.is_use = args.is_use;
    }
    if (args.reg_date !== undefined && args.reg_date !== null) {
      this.reg_date = args.reg_date;
    }
    if (args.email !== undefined && args.email !== null) {
      this.email = args.email;
    }
  }
};
AdminUser.prototype = {};
AdminUser.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.passwd = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.team = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.BOOL) {
        this.is_use = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRING) {
        this.reg_date = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRING) {
        this.email = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AdminUser.prototype.write = function(output) {
  output.writeStructBegin('AdminUser');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 2);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.passwd !== null && this.passwd !== undefined) {
    output.writeFieldBegin('passwd', Thrift.Type.STRING, 3);
    output.writeString(this.passwd);
    output.writeFieldEnd();
  }
  if (this.team !== null && this.team !== undefined) {
    output.writeFieldBegin('team', Thrift.Type.STRING, 4);
    output.writeString(this.team);
    output.writeFieldEnd();
  }
  if (this.is_use !== null && this.is_use !== undefined) {
    output.writeFieldBegin('is_use', Thrift.Type.BOOL, 5);
    output.writeBool(this.is_use);
    output.writeFieldEnd();
  }
  if (this.reg_date !== null && this.reg_date !== undefined) {
    output.writeFieldBegin('reg_date', Thrift.Type.STRING, 6);
    output.writeString(this.reg_date);
    output.writeFieldEnd();
  }
  if (this.email !== null && this.email !== undefined) {
    output.writeFieldBegin('email', Thrift.Type.STRING, 7);
    output.writeString(this.email);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

