<?php
namespace Ridibooks\Cms\Thrift\AdminMenu;
/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


/**
 * AdminMenu 서비스
 */
interface AdminMenuServiceIf {
  /**
   * @param bool $isUse
   * @return \Ridibooks\Cms\Thrift\AdminMenu\AdminMenu[] AdminMenuCollection 엔티티
   * 
   * @throws \Ridibooks\Cms\Thrift\Errors\UserException
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getMenuList($isUse);
  /**
   * @return \Ridibooks\Cms\Thrift\AdminMenu\AdminMenu[] AdminMenuCollection 엔티티
   * 
   * @throws \Ridibooks\Cms\Thrift\Errors\UserException
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getAllMenuList();
  /**
   * @return \Ridibooks\Cms\Thrift\AdminMenu\AdminMenuAjax[]
   * @throws \Ridibooks\Cms\Thrift\Errors\UserException
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getAllMenuAjax();
  /**
   * @param int[] $menuIds
   * @return \Ridibooks\Cms\Thrift\AdminMenu\AdminMenu[] AdminMenuCollection 엔티티
   * 
   * @throws \Ridibooks\Cms\Thrift\Errors\UserException
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getMenus(array $menuIds);
  /**
   * @param int $menuId
   * @return string[]
   * @throws \Ridibooks\Cms\Thrift\Errors\UserException
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getAdminIdsByMenuId($menuId);
}


