<?php
namespace Ridibooks\Cms\Thrift\Errors;

/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


/**
 * 에러 코드
 */
final class ErrorCode {
  /**
   * 일반적인 클라이언트 에러
   */
  const BAD_REQUEST = 400;
  /**
   * 요청한 리소스가 서버에 없음
   */
  const NOT_FOUND = 404;
  /**
   * 클라이언트가 제시한 파라미터 값/형식이 기대 요건을 충족하지 않음
   */
  const UNPROCESSIBLE_ENTITY = 422;
  /**
   * General server error
   */
  const INTERNAL_SERVER_ERROR = 500;
  static public $__names = array(
    400 => 'BAD_REQUEST',
    404 => 'NOT_FOUND',
    422 => 'UNPROCESSIBLE_ENTITY',
    500 => 'INTERNAL_SERVER_ERROR',
  );
}

