<?php
namespace Ridibooks\Cms\Thrift\AdminAuth;
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


/**
 * AdminAuth 서비스
 */
interface AdminAuthServiceIf {
  /**
   * @param string $hash
   * @param string $checkUrl
   * @param string $adminId
   * @return bool
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   * @throws \Ridibooks\Cms\Thrift\Errors\UnauthorizedException
   */
  public function hasHashAuth($hash, $checkUrl, $adminId);
  /**
   * @param string $checkUrl
   * @param string $adminId
   * @return string[]
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getCurrentHashArray($checkUrl, $adminId);
  /**
   * @param string $adminId
   * @return \Ridibooks\Cms\Thrift\AdminAuth\AdminMenu[]
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getAdminMenu($adminId);
  /**
   * @param string $token
   * @param string[] $methods
   * @param string $check_url
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   * @throws \Ridibooks\Cms\Thrift\Errors\NoTokenException
   * @throws \Ridibooks\Cms\Thrift\Errors\MalformedTokenException
   * @throws \Ridibooks\Cms\Thrift\Errors\ExpiredTokenException
   * @throws \Ridibooks\Cms\Thrift\Errors\UnauthorizedException
   */
  public function authorize($token, array $methods, $check_url);
  /**
   * @param string $token
   * @param string[] $tags
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   * @throws \Ridibooks\Cms\Thrift\Errors\NoTokenException
   * @throws \Ridibooks\Cms\Thrift\Errors\MalformedTokenException
   * @throws \Ridibooks\Cms\Thrift\Errors\ExpiredTokenException
   * @throws \Ridibooks\Cms\Thrift\Errors\UnauthorizedException
   */
  public function authorizeByTag($token, array $tags);
}


