<?php
namespace Ridibooks\Cms\Thrift\AdminTag;
/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface AdminTagServiceIf {
  /**
   * @param int[] $tag_ids
   * @return string[]
   * @throws \Ridibooks\Cms\Thrift\Errors\UserException
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getAdminIdsFromTags(array $tag_ids);
  /**
   * @param int $tag_id
   * @return \Ridibooks\Cms\Thrift\AdminMenu\AdminMenu[] AdminMenuCollection 엔티티
   * 
   * @throws \Ridibooks\Cms\Thrift\Errors\UserException
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getAdminTagMenus($tag_id);
  /**
   * @param string $check_url
   * @param int $tag_id
   * @return string[]
   * @throws \Ridibooks\Cms\Thrift\Errors\UserException
   * @throws \Ridibooks\Cms\Thrift\Errors\SystemException
   */
  public function getMappedAdminMenuHashes($check_url, $tag_id);
}


