# -*- coding: utf-8 -*-
#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:coding=utf-8
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
import sys
import cmssdk.Errors.ttypes

from thrift.transport import TTransport


class AdminMenu(object):
    """
    AdminMenu 엔티티

    Attributes:
     - id
     - menu_title
     - menu_url
     - menu_deep
     - menu_order
     - is_use
     - is_show
     - reg_date
     - is_newtab
    """

    thrift_spec = (
        None,  # 0
        (1, TType.I32, 'id', None, None, ),  # 1
        (2, TType.STRING, 'menu_title', 'UTF8', None, ),  # 2
        (3, TType.STRING, 'menu_url', 'UTF8', None, ),  # 3
        (4, TType.I32, 'menu_deep', None, None, ),  # 4
        (5, TType.I32, 'menu_order', None, None, ),  # 5
        (6, TType.BOOL, 'is_use', None, None, ),  # 6
        (7, TType.BOOL, 'is_show', None, None, ),  # 7
        (8, TType.STRING, 'reg_date', 'UTF8', None, ),  # 8
        (9, TType.BOOL, 'is_newtab', None, None, ),  # 9
    )

    def __init__(self, id=None, menu_title=None, menu_url=None, menu_deep=None, menu_order=None, is_use=None, is_show=None, reg_date=None, is_newtab=None,):
        self.id = id
        self.menu_title = menu_title
        self.menu_url = menu_url
        self.menu_deep = menu_deep
        self.menu_order = menu_order
        self.is_use = is_use
        self.is_show = is_show
        self.reg_date = reg_date
        self.is_newtab = is_newtab

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.menu_title = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.menu_url = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.menu_deep = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I32:
                    self.menu_order = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.BOOL:
                    self.is_use = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.BOOL:
                    self.is_show = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.STRING:
                    self.reg_date = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 9:
                if ftype == TType.BOOL:
                    self.is_newtab = iprot.readBool()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('AdminMenu')
        if self.id is not None:
            oprot.writeFieldBegin('id', TType.I32, 1)
            oprot.writeI32(self.id)
            oprot.writeFieldEnd()
        if self.menu_title is not None:
            oprot.writeFieldBegin('menu_title', TType.STRING, 2)
            oprot.writeString(self.menu_title.encode('utf-8') if sys.version_info[0] == 2 else self.menu_title)
            oprot.writeFieldEnd()
        if self.menu_url is not None:
            oprot.writeFieldBegin('menu_url', TType.STRING, 3)
            oprot.writeString(self.menu_url.encode('utf-8') if sys.version_info[0] == 2 else self.menu_url)
            oprot.writeFieldEnd()
        if self.menu_deep is not None:
            oprot.writeFieldBegin('menu_deep', TType.I32, 4)
            oprot.writeI32(self.menu_deep)
            oprot.writeFieldEnd()
        if self.menu_order is not None:
            oprot.writeFieldBegin('menu_order', TType.I32, 5)
            oprot.writeI32(self.menu_order)
            oprot.writeFieldEnd()
        if self.is_use is not None:
            oprot.writeFieldBegin('is_use', TType.BOOL, 6)
            oprot.writeBool(self.is_use)
            oprot.writeFieldEnd()
        if self.is_show is not None:
            oprot.writeFieldBegin('is_show', TType.BOOL, 7)
            oprot.writeBool(self.is_show)
            oprot.writeFieldEnd()
        if self.reg_date is not None:
            oprot.writeFieldBegin('reg_date', TType.STRING, 8)
            oprot.writeString(self.reg_date.encode('utf-8') if sys.version_info[0] == 2 else self.reg_date)
            oprot.writeFieldEnd()
        if self.is_newtab is not None:
            oprot.writeFieldBegin('is_newtab', TType.BOOL, 9)
            oprot.writeBool(self.is_newtab)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class AdminMenuAjax(object):
    """
    Attributes:
     - id
     - menu_id
     - ajax_url
    """

    thrift_spec = (
        None,  # 0
        (1, TType.I32, 'id', None, None, ),  # 1
        (2, TType.I32, 'menu_id', None, None, ),  # 2
        (3, TType.STRING, 'ajax_url', 'UTF8', None, ),  # 3
    )

    def __init__(self, id=None, menu_id=None, ajax_url=None,):
        self.id = id
        self.menu_id = menu_id
        self.ajax_url = ajax_url

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, (self.__class__, self.thrift_spec))
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.menu_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.ajax_url = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
            return
        oprot.writeStructBegin('AdminMenuAjax')
        if self.id is not None:
            oprot.writeFieldBegin('id', TType.I32, 1)
            oprot.writeI32(self.id)
            oprot.writeFieldEnd()
        if self.menu_id is not None:
            oprot.writeFieldBegin('menu_id', TType.I32, 2)
            oprot.writeI32(self.menu_id)
            oprot.writeFieldEnd()
        if self.ajax_url is not None:
            oprot.writeFieldBegin('ajax_url', TType.STRING, 3)
            oprot.writeString(self.ajax_url.encode('utf-8') if sys.version_info[0] == 2 else self.ajax_url)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
